// apps/client/src/components/dataset/PaginationWrapper.vue
<script setup lang="ts">
import { computed } from 'vue'
import {
  Pagination,
  PaginationContent,
  PaginationEllipsis,
  PaginationFirst,
  PaginationItem,
  PaginationLast,
  PaginationNext,
  PaginationPrevious,
} from '@/components/ui/pagination'

interface Props {
  total: number
  currentPage: number
  itemsPerPage: number
  disabled?: boolean
}

interface Emits {
  (e: 'page-change', page: number): void
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
})

const emit = defineEmits<Emits>()

const totalPages = computed(() => Math.ceil(props.total / props.itemsPerPage))

const handlePageChange = (page: number) => {
  if (page === props.currentPage || props.disabled) return
  emit('page-change', page)
}

const getVisiblePages = () => {
  const pages: (number | string)[] = []
  const total = totalPages.value
  const current = props.currentPage

  if (total <= 7) {
    for (let i = 1; i <= total; i++) {
      pages.push(i)
    }
  } else {
    pages.push(1)

    if (current > 3) {
      pages.push('...')
    }

    const start = Math.max(2, current - 1)
    const end = Math.min(total - 1, current + 1)

    for (let i = start; i <= end; i++) {
      pages.push(i)
    }

    if (current < total - 2) {
      pages.push('...')
    }

    if (total > 1) {
      pages.push(total)
    }
  }

  return pages
}
</script>

<template>
  <div v-if="totalPages > 1" class="flex justify-center">
    <Pagination
      :total="total"
      :page="currentPage"
      :items-per-page="itemsPerPage"
      @page-change="handlePageChange"
    >
      <PaginationContent>
        <PaginationFirst :disabled="currentPage === 1 || disabled" @click="handlePageChange(1)" />
        <PaginationPrevious
          :disabled="currentPage === 1 || disabled"
          @click="handlePageChange(currentPage - 1)"
        />

        <!-- Pages numérotées -->
        <template v-for="page in getVisiblePages()" :key="page">
          <PaginationItem v-if="page === '...'" :value="-1" as="span" class="text-gray-400">
            <PaginationEllipsis />
          </PaginationItem>
          <PaginationItem v-else :value="page as number">
            <button
              :disabled="disabled"
              :class="[
                'px-3 py-2 text-sm rounded-md transition-colors',
                page === currentPage ? 'bg-blue-600 text-white' : 'text-gray-700 hover:bg-gray-100',
                disabled && 'opacity-50 cursor-not-allowed',
              ]"
              @click="handlePageChange(page as number)"
            >
              {{ page }}
            </button>
          </PaginationItem>
        </template>

        <PaginationNext
          :disabled="currentPage === totalPages || disabled"
          @click="handlePageChange(currentPage + 1)"
        />
        <PaginationLast
          :disabled="currentPage === totalPages || disabled"
          @click="handlePageChange(totalPages)"
        />
      </PaginationContent>
    </Pagination>
  </div>
</template>

// apps/next/components/dataset/pagination-wrapper.tsx
'use client'

import { useMemo } from 'react'
import { cn } from '@/lib/utils'
import { ChevronFirst, ChevronLast, ChevronLeft, ChevronRight } from 'lucide-react'
import { Button } from '@/components/ui/button'

interface PaginationWrapperProps {
  total: number
  currentPage: number
  itemsPerPage: number
  disabled?: boolean
  onPageChange: (page: number) => void
  className?: string
}

export function PaginationWrapper({
  total,
  currentPage,
  itemsPerPage,
  disabled = false,
  onPageChange,
  className,
}: PaginationWrapperProps) {
  const totalPages = Math.ceil(total / itemsPerPage)

  const handlePageChange = (page: number) => {
    if (page === currentPage || disabled) return
    onPageChange(page)
  }

  const visiblePages = useMemo(() => {
    const pages: (number | string)[] = []

    if (totalPages <= 7) {
      for (let i = 1; i <= totalPages; i++) {
        pages.push(i)
      }
    } else {
      pages.push(1)

      if (currentPage > 3) {
        pages.push('...')
      }

      const start = Math.max(2, currentPage - 1)
      const end = Math.min(totalPages - 1, currentPage + 1)

      for (let i = start; i <= end; i++) {
        pages.push(i)
      }

      if (currentPage < totalPages - 2) {
        pages.push('...')
      }

      if (totalPages > 1) {
        pages.push(totalPages)
      }
    }

    return pages
  }, [totalPages, currentPage])

  if (totalPages <= 1) {
    return null
  }

  return (
    <div className={cn('flex justify-center items-center gap-1', className)}>
      <Button
        variant="outline"
        size="icon"
        disabled={currentPage === 1 || disabled}
        onClick={() => handlePageChange(1)}
      >
        <ChevronFirst className="h-4 w-4" />
      </Button>

      <Button
        variant="outline"
        size="icon"
        disabled={currentPage === 1 || disabled}
        onClick={() => handlePageChange(currentPage - 1)}
      >
        <ChevronLeft className="h-4 w-4" />
      </Button>

      {visiblePages.map((page, index) =>
        page === '...' ? (
          <span key={`ellipsis-${index}`} className="px-2 text-gray-400">
            ...
          </span>
        ) : (
          <button
            key={page}
            disabled={disabled}
            className={cn(
              'px-3 py-2 text-sm rounded-md transition-colors',
              page === currentPage
                ? 'bg-primary text-primary-foreground'
                : 'text-gray-700 hover:bg-gray-100',
              disabled && 'opacity-50 cursor-not-allowed',
            )}
            onClick={() => handlePageChange(page as number)}
          >
            {page}
          </button>
        ),
      )}

      <Button
        variant="outline"
        size="icon"
        disabled={currentPage === totalPages || disabled}
        onClick={() => handlePageChange(currentPage + 1)}
      >
        <ChevronRight className="h-4 w-4" />
      </Button>

      <Button
        variant="outline"
        size="icon"
        disabled={currentPage === totalPages || disabled}
        onClick={() => handlePageChange(totalPages)}
      >
        <ChevronLast className="h-4 w-4" />
      </Button>
    </div>
  )
}
